In [56]:
import numpy as np
import pandas as pd
import numpy_financial as nf

In [57]:
a = np.array([[2,3],[5,2]])
a

array([[2, 3],
       [5, 2]])

In [58]:
d= np.array([[1,2,3,4,5],[2,4,6,8,10],[5,6,7,8,9]])
print(d)

[[ 1  2  3  4  5]
 [ 2  4  6  8 10]
 [ 5  6  7  8  9]]


In [59]:
print(d[2][2])
print(d[1,2])
print(d[1:,:3])

7
6
[[2 4 6]
 [5 6 7]]


In [60]:
print(d[:,4:])

[[ 5]
 [10]
 [ 9]]


In [61]:
print(d.shape)
e = np.array([1,2,3,4])
e.shape

(3, 5)


(4,)

In [62]:
print(d.dtype)

int64


In [63]:
np.zeros(4)

array([0., 0., 0., 0.])

In [64]:
np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [65]:
print(np.arange(2,10))
print(np.arange(10))
print(np.arange(1,10,2))

[2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


In [66]:
print(np.ones((2,3)))

[[1. 1. 1.]
 [1. 1. 1.]]


In [67]:
data = np.arange(1,5)
print(data.dtype)

data = data.astype('float64')
print(data)

data = data.astype('int64')
print(data)

int64
[1. 2. 3. 4.]
[1 2 3 4]


In [68]:
a = np.ones((2,3))
print(a)

b = a.transpose()
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [69]:
arr1 = np.array([[2,3,4],[6,7,8]])
arr2 = np.array([[12,13,14],[26,37,48]])
print(arr1+arr2) # 배열끼리 더하면 같은 자리끼리 더한다.

[[14 16 18]
 [32 44 56]]


In [70]:
print(arr1*arr2) # 같은 자리끼리 곱셉
print(arr1/arr2) # 같은 자리끼리 나눗셈

[[ 24  39  56]
 [156 259 384]]
[[0.16666667 0.23076923 0.28571429]
 [0.23076923 0.18918919 0.16666667]]


In [71]:
arr3 = np.array([100,200,300])
arr4 = np.array([[2],[4]])

print(arr1+arr3) # 행이나 열 둘중 하나는 일치해야 함
print(arr1+ arr4)

[[102 203 304]
 [106 207 308]]
[[ 4  5  6]
 [10 11 12]]


In [72]:
d = np.array([[1,2,3,4,5],[2,3,4,5,6],[5,7,8,9,9]])
d_list = [[1,2,3,4,5],[2,3,4,5,6],[5,7,8,9,9]]
print(type(d_list))

<class 'list'>


In [73]:
#d_list[:2] = 0 TypeError: can only assign an iterable

In [74]:
d[:2] =0
print(d)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [5 7 8 9 9]]


In [75]:
import usecsv
quest = np.array(usecsv.switch(usecsv.opencsv('quest.csv')))
print(quest)

[[1. 2. 1. 2. 2.]
 [1. 3. 2. 3. 2.]
 [1. 4. 3. 3. 3.]
 [2. 5. 4. 4. 4.]
 [2. 5. 6. 2. 5.]
 [3. 6. 4. 2. 5.]
 [3. 5. 4. 1. 6.]
 [3. 5. 5. 1. 3.]]


In [77]:
quest = quest.astype('int64')
print(quest>5)


[[False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False  True False False]
 [False  True False False False]
 [False False False False  True]
 [False False False False False]]


In [79]:
quest[quest>5]=5
print(quest)

[[1 2 1 2 2]
 [1 3 2 3 2]
 [1 4 3 3 3]
 [2 5 4 4 4]
 [2 5 5 2 5]
 [3 5 4 2 5]
 [3 5 4 1 5]
 [3 5 5 1 3]]


In [82]:
discount = 0.05
cashflow = 100

def persentvalue(n):
    return(cashflow/((1+discount)**n))
print(persentvalue(5))

78.35261664684589


In [83]:
for i in range(20):
    print(persentvalue(i))

100.0
95.23809523809524
90.70294784580499
86.3837598531476
82.27024747918819
78.35261664684589
74.62153966366274
71.06813301301213
67.6839362028687
64.46089162177971
61.39132535407592
58.46792890864373
55.68374181775592
53.03213506452945
50.506795299551854
48.101709809096995
45.811152199140004
43.62966876108571
41.5520654867483
39.57339570166504


In [84]:
cf = [-750, -250, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100]
cashflow = np.array(cf)

In [85]:
# 사업 수익률 구하기 6.5% - 4.5%
print(nf.irr(cashflow))
# 순 현재가치
print(nf.npv(0.045, cashflow))

0.06434936937255564
174.4011295118405
