In [37]:
import numpy as np
import pandas as pd
import numpy_financial as nf

In [38]:
a = np.array([[2,3],[5,2]])
a

array([[2, 3],
       [5, 2]])

In [39]:
d= np.array([[1,2,3,4,5],[2,4,6,8,10],[5,6,7,8,9]])
print(d)

[[ 1  2  3  4  5]
 [ 2  4  6  8 10]
 [ 5  6  7  8  9]]


In [40]:
print(d[2][2])
print(d[1,2])
print(d[1:,:3])

7
6
[[2 4 6]
 [5 6 7]]


In [41]:
print(d[:,4:])

[[ 5]
 [10]
 [ 9]]


In [42]:
print(d.shape)
e = np.array([1,2,3,4])
e.shape

(3, 5)


(4,)

In [43]:
print(d.dtype)

int64


In [44]:
np.zeros(4)

array([0., 0., 0., 0.])

In [45]:
np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [46]:
print(np.arange(2,10))
print(np.arange(10))
print(np.arange(1,10,2))

[2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


In [47]:
print(np.ones((2,3)))

[[1. 1. 1.]
 [1. 1. 1.]]


In [48]:
data = np.arange(1,5)
print(data.dtype)

data = data.astype('float64')
print(data)

data = data.astype('int64')
print(data)

int64
[1. 2. 3. 4.]
[1 2 3 4]


In [49]:
a = np.ones((2,3))
print(a)

b = a.transpose()
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [50]:
arr1 = np.array([[2,3,4],[6,7,8]])
arr2 = np.array([[12,13,14],[26,37,48]])
print(arr1+arr2) # 배열끼리 더하면 같은 자리끼리 더한다.

[[14 16 18]
 [32 44 56]]


In [51]:
print(arr1*arr2) # 같은 자리끼리 곱셉
print(arr1/arr2) # 같은 자리끼리 나눗셈

[[ 24  39  56]
 [156 259 384]]
[[0.16666667 0.23076923 0.28571429]
 [0.23076923 0.18918919 0.16666667]]


In [52]:
arr3 = np.array([100,200,300])
arr4 = np.array([[2],[4]])

print(arr1+arr3) # 행이나 열 둘중 하나는 일치해야 함
print(arr1+ arr4)

[[102 203 304]
 [106 207 308]]
[[ 4  5  6]
 [10 11 12]]


In [53]:
d = np.array([[1,2,3,4,5],[2,3,4,5,6],[5,7,8,9,9]])
d_list = [[1,2,3,4,5],[2,3,4,5,6],[5,7,8,9,9]]
print(type(d_list))

<class 'list'>


In [54]:
#d_list[:2] = 0 TypeError: can only assign an iterable

In [55]:
d[:2] =0
print(d)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [5 7 8 9 9]]
